<?php

return [
    'super_admin' => [
        'permissions' => [
            'manage_users',
            'manage_roles',
            'view_any_users',
            'view_users',
            'create_users',
            'update_users',
            'delete_users',
            'view_any_brands',
            'view_brands',
            'create_brands',
            'update_brands',
            'delete_brands',
            'view_any_products',
            'view_products',
            'create_products',
            'update_products',
            'delete_products',
            'view_any_categories',
            'view_categories',
            'create_categories',
            'update_categories',
            'delete_categories',
        ],
    ],
    'admin' => [
        'permissions' => [
            'manage_users',
            'view_any_users',
            'view_users',
            'create_users',
            'update_users',
            'delete_users',
            'view_any_brands',
            'view_brands',
            'create_brands',
            'update_brands',
            'delete_brands',
            'view_any_products',
            'view_products',
            'create_products',
            'update_products',
            'delete_products',
            'view_any_categories',
            'view_categories',
            'create_categories',
            'update_categories',
            'delete_categories',
        ],
    ],
    'user' => [
        'permissions' => [
            'view_own_profile',
            'update_own_profile',
        ],
    ],
    'shopowner' => [
        'permissions' => [
            'view_any_brands',
            'view_brands',
            'create_brands',
            'update_brands',
            'delete_brands',
            'view_any_products',
            'view_products',
            'create_products',
            'update_products',
            'delete_products',
            'view_any_categories',
            'view_categories',
            'create_categories',
            'update_categories',
            'delete_categories',
        ],
    ],
];
